# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            deso
tagline:          "Daniel Müller's Projects"
description:      "Projects and random notes"
url:              https://github.com/d-e-s-o

author:
  name:           "Daniel Müller"
  url:            https://github.com/d-e-s-o

paginate:         5

github:
  repo:           https://github.com/d-e-s-o/d-e-s-o.github.io
